# Predictive Maintenance HVAC

## Import Libraries

In [21]:
import pandas as pd

## Load Dataset

In [22]:
df = pd.read_parquet("hvac_data_cleaned.parquet")

## Data Inspection

In [5]:
df.head()

,timestamp,on_off,damper,active_energy,co2_1,ambient_humidity,active_power,power_generated,high_pressure_1,high_pressure_2,low_pressure_1,low_pressure_2,high_pressure_3,low_pressure_3,outside_temp,outlet_temp,inlet_temp,summer_SP_temp,winter_SP_temp,ambient_temp
0,2022-06-01 00:00:00,0.0,0.0,762617.80,975.0,35.0,0.51,4.0,15.09,15.0,15.27,15.1,15.2,15.2,23.9,24.3,22.9,22.5,18.0,23.4
1,2022-06-01 00:05:00,0.0,0.0,NaN,977.0,35.0,0.51,NaN,15.03,14.9,15.21,15.0,15.2,15.1,23.8,24.3,22.8,22.5,18.0,23.3
2,2022-06-01 00:10:00,0.0,0.0,NaN,975.0,35.0,0.51,NaN,15.03,14.8,15.15,15.0,15.1,15.1,23.6,24.2,22.6,22.5,18.0,23.4
3,2022-06-01 00:15:00,0.0,0.0,762617.99,975.0,35.0,0.51,4.0,14.96,14.8,15.15,14.9,15.1,15.0,23.6,24.0,22.4,22.5,18.0,23.3
4,2022-06-01 00:20:00,0.0,0.0,NaN,975.0,35.0,0.51,NaN,14.90,14.7,15.09,14.9,15.0,14.9,23.4,24.0,22.3,22.5,18.0,23.3

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25632 entries, 0 to 25631
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   timestamp         25632 non-null  datetime64[ns]
 1   on_off            25557 non-null  float64
 2   damper            25555 non-null  float64
 3   active_energy     8518 non-null   float64
 4   co2_1             25554 non-null  float64
 5   ambient_humidity  25296 non-null  float64
 6   active_power      25560 non-null  float64
 7   power_generated   8544 non-null   float64
 8   high_pressure_1   25553 non-null  float64
 9   high_pressure_2   25556 non-null  float64
 10  low_pressure_1    25553 non-null  float64
 11  low_pressure_2    25556 non-null  float64
 12  high_pressure_3   25556 non-null  float64
 13  low_pressure_3    25556 non-null  float64
 14  outside_temp      25555 non-null  float64
 15  outlet_temp       25556 non-null  float64
 16  inlet_temp        25557 non-null  float64
 17  summer_SP_temp    25556 non-null  float64
 18  winter_SP_temp    25555 non-null  float64
 19  ambient_temp      25490 non-null  float64
dtypes: datetime64[ns](1), float64(19)
memory usage: 3.9 MB

In [7]:
df.columns

Index(['timestamp', 'on_off', 'damper', 'active_energy', 'co2_1',
       'ambient_humidity', 'active_power', 'power_generated',
       'high_pressure_1', 'high_pressure_2', 'low_pressure_1',
       'low_pressure_2', 'high_pressure_3', 'low_pressure_3', 'outside_temp',
       'outlet_temp', 'inlet_temp', 'summer_SP_temp', 'winter_SP_temp',
       'ambient_temp'],
      dtype='object')

## Missing Value Analysis

In [8]:
df.isnull().sum()

timestamp               0
on_off                 75
damper                 77
active_energy       17114
co2_1                  78
ambient_humidity      336
active_power           72
power_generated     17088
high_pressure_1        79
high_pressure_2        76
low_pressure_1         79
low_pressure_2         76
high_pressure_3        76
low_pressure_3         76
outside_temp           77
outlet_temp            76
inlet_temp             75
summer_SP_temp         76
winter_SP_temp         77
ambient_temp          142
dtype: int64

In [9]:
df["timestamp"].dtype

dtype('<M8[ns]')

In [10]:
df.describe()

,timestamp,on_off,damper,active_energy,co2_1,ambient_humidity,active_power,power_generated,high_pressure_1,high_pressure_2,low_pressure_1,low_pressure_2,high_pressure_3,low_pressure_3,outside_temp,outlet_temp,inlet_temp,summer_SP_temp,winter_SP_temp,ambient_temp
count,25632,25557.000000,25555.000000,8518.000000,25554.000000,25296.000000,25560.000000,8544.000000,25553.000000,25556.000000,25553.000000,25556.000000,25556.000000,25556.000000,25555.000000,25556.000000,25557.000000,25556.000000,25555.000000,25490.000000
mean,2022-07-16 12:13:40.786516992,0.429002,8.311368,794381.141334,1115.937387,39.317521,13.963495,24.113179,19.287211,19.251600,13.523317,13.554883,15.813973,15.732251,29.694369,21.703952,25.067238,22.924542,18.743221,24.181012
min,2022-06-01 00:00:00,0.000000,0.000000,762617.800000,955.000000,0.000000,0.470000,0.000000,10.220000,11.000000,7.080000,7.200000,11.200000,11.100000,13.800000,7.100000,14.300000,22.000000,18.000000,0.000000
25%,2022-06-23 05:58:45,0.000000,0.000000,777009.267500,1025.000000,35.000000,0.510000,3.000000,14.720000,14.700000,9.790000,10.300000,14.700000,14.600000,24.300000,16.000000,22.400000,22.500000,18.000000,23.200000
50%,2022-07-16 11:57:30,0.000000,0.000000,793724.410000,1115.000000,39.000000,0.550000,6.000000,17.000000,17.100000,13.980000,13.800000,15.600000,15.500000,29.300000,21.100000,23.900000,22.500000,18.000000,24.300000
75%,2022-08-08 17:56:15,1.000000,13.000000,813164.227500,1187.000000,44.000000,29.870000,48.000000,24.020000,24.100000,16.070000,16.000000,16.400000,16.400000,35.400000,25.800000,25.600000,23.600000,19.500000,25.000000
max,2022-08-30 23:55:00,1.000000,100.000000,825143.660000,1482.000000,62.000000,57.870000,77.000000,34.300000,33.500000,24.820000,24.300000,25.500000,25.500000,50.000000,50.100000,54.400000,25.000000,22.000000,27.100000
std,NaN,0.494943,16.820421,19434.389352,101.445789,6.444740,17.659089,23.823249,5.734787,5.521055,3.786948,3.503190,2.147010,2.136828,6.883145,7.420254,6.155406,0.946479,1.204528,1.283968

In [11]:
df.isnull().sum().sort_values(ascending=False)

active_energy       17114
power_generated     17088
ambient_humidity      336
ambient_temp          142
high_pressure_1        79
low_pressure_1         79
co2_1                  78
damper                 77
outside_temp           77
winter_SP_temp         77
high_pressure_2        76
low_pressure_2         76
high_pressure_3        76
low_pressure_3         76
outlet_temp            76
summer_SP_temp         76
on_off                 75
inlet_temp             75
active_power           72
timestamp               0
dtype: int64

In [23]:
(df.isnull().sum() / len(df)) * 100

timestamp            0.000000
on_off               0.292603
damper               0.300406
active_energy       66.768102
co2_1                0.304307
ambient_humidity     1.310861
active_power         0.280899
power_generated     66.666667
high_pressure_1      0.308208
high_pressure_2      0.296504
low_pressure_1       0.308208
low_pressure_2       0.296504
high_pressure_3      0.296504
low_pressure_3       0.296504
outside_temp         0.300406
outlet_temp          0.296504
inlet_temp           0.292603
summer_SP_temp       0.296504
winter_SP_temp       0.300406
ambient_temp         0.553995
dtype: float64

## Dropping Highly Missing Columns

In [13]:
df.drop(columns=["active_energy", "power_generated"], inplace=True)

In [14]:
df.columns

Index(['timestamp', 'on_off', 'damper', 'co2_1', 'ambient_humidity',
       'active_power', 'high_pressure_1', 'high_pressure_2', 'low_pressure_1',
       'low_pressure_2', 'high_pressure_3', 'low_pressure_3', 'outside_temp',
       'outlet_temp', 'inlet_temp', 'summer_SP_temp', 'winter_SP_temp',
       'ambient_temp'],
      dtype='object')

In [15]:
df.isnull().sum().sort_values(ascending=False)

ambient_humidity    336
ambient_temp        142
high_pressure_1      79
low_pressure_1       79
co2_1                78
damper               77
winter_SP_temp       77
outside_temp         77
low_pressure_3       76
summer_SP_temp       76
outlet_temp          76
low_pressure_2       76
high_pressure_3      76
high_pressure_2      76
on_off               75
inlet_temp           75
active_power         72
timestamp             0
dtype: int64

## Filling Remaining Missing Values

In [16]:
df = df.fillna(df.mean(numeric_only=True))

## Cleaned Dataset Overview

In [24]:
df.isnull().sum()

timestamp               0
on_off                 75
damper                 77
active_energy       17114
co2_1                  78
ambient_humidity      336
active_power           72
power_generated     17088
high_pressure_1        79
high_pressure_2        76
low_pressure_1         79
low_pressure_2         76
high_pressure_3        76
low_pressure_3         76
outside_temp           77
outlet_temp            76
inlet_temp             75
summer_SP_temp         76
winter_SP_temp         77
ambient_temp          142
dtype: int64

## Exporting Cleaned Dataset

In [25]:
df.to_csv("cleaned_hvac_dataset.csv", index=False)

## Conclusion

- Cleaned and preprocessed the HVAC dataset.
- Removed highly missing columns and handled remaining missing values.
- Verified datetime formatting for time-based analysis.
- Exported a cleaned dataset for future predictive maintenance analysis.